name: "CI - Bump Version"

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump-version:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release-')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout main
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure git user and email
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"    

      - name: Delete Release Branch
        run: |
           echo "Deleting branch: ${{ github.head_ref }}"
           gh api -X DELETE /repos/${{ github.repository }}/git/refs/heads/${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump to the next snapshot
        run: |
          OLD_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          # We bump
          ./mvnw -ntp -B versions:set -DnextSnapshot=true versions:commit
          
          # Got the new version
          NEW_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          # Replace the old with the new version within the properties, markdown and sample pom.xml files
          find . \( -path "./.idea" -o -path "./.mvn" -o -path "./test-project" -o -name "target" \) -prune -o \
            -type f \( -name "*.xml" -o -name "*.properties" -o -name "*.md" -o -path "./sample/*/pom.xml" \) -print \
            -exec sed -i -e "s/$OLD_VERSION/$NEW_VERSION/g" {} +
          
          git add .
          git commit -m "chore: Bump the project to the version: $NEW_VERSION [skip ci]"
          git push origin main